cilium:
  MTU: 9000
  bpf:
    masquerade: true
  encryption:
    enabled: false
    type: wireguard
  hostFirewall:
    enabled: true
  hubble:
    enabled: true
    metrics:
      enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    relay:
      enabled: true
    ui:
      enabled: true
#  ipam:
#    mode: kubernetes
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  kubeProxyReplacement: disabled
  policyAuditMode: true
  policyEnforcementMode: default

