{
 "title": "#{ title }#",
 "description": "CEPH OSD Status.",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": {
     "query": "label_values(ceph_osd_up, ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Status / Total OSDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_up{ceph_daemon=\"$osd\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_in{ceph_daemon=\"$osd\"})"
    }
   ]
  },
  {
   "title": "Total OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_osd_up)"
    }
   ]
  },
  {
   "title": "OSD: $osd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PGs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_numpg{ceph_daemon=~\"$osd\"})",
     "legendFormat": "Number of PGs"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_numpg)",
     "legendFormat": "Average Number of PGs in the Cluster"
    }
   ]
  },
  {
   "title": "OSD Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"}-ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"}/ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"})"
    }
   ]
  },
  {
   "title": "Latency, Storage, Utilization Varience",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_apply_latency_ms{ceph_daemon='$osd'})"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_osd_commit_latency_ms{ceph_daemon='$osd'})"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum without (instance) (rate(ceph_osd_op_r_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon='$osd'}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum without (instance) (rate(ceph_osd_op_w_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon='$osd'}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_r_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon='$osd'}[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{ceph_daemon='$osd'}[5m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon='$osd'}[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{ceph_daemon='$osd'})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg without (instance, ceph_daemon)(ceph_osd_commit_latency_ms{ceph_daemon='$osd'})",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}