apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: debug
spec:
  selector:
    matchLabels:
      name: debug
  template:
    metadata:
      labels:
        name: debug
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - image: praqma/network-multitool:fedora # https://github.com/wbitt/Network-MultiTool
          command:
            - "sleep"
            - "604800"
          imagePullPolicy: IfNotPresent
          name: debug
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
