---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:=192.168.0.0/16}
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:=172.26.0.0/16}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: PacketCluster
    name: "${CLUSTER_NAME}"
  controlPlaneRef:
    kind: TalosControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "${CLUSTER_NAME}-control-plane"

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  projectID: ${PROJECT_ID}
  facility: ${FACILITY}
  vipManager: "KUBE_VIP"
  controlPlaneEndpoint:
    host: ${TOEM_CP_ENDPOINT}
    port: 6443

---
## Control plane configs
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  version: ${KUBERNETES_VERSION}
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: PacketMachineTemplate
    name: "${CLUSTER_NAME}-control-plane"
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_VERSION}
      configPatches:
        - op: add
          path: /cluster/inlineManifests/0
          value:
            name: cpem-secret
            contents: |
              apiVersion: v1
              data:
                cloud-sa.json: ${TOEM_CPEM_SECRET}
              kind: Secret
              metadata:
                name: metal-cloud-config
                namespace: kube-system
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
        - op: add
          path: /machine/network
          value:
            interfaces: []
        - op: add
          path: /machine/network/interfaces/0
          value:
            interface: eth3
            vip:
              ip: ${TOEM_CP_ENDPOINT}
              equinixMetal:
                apiToken: ${PACKET_API_KEY}
        - op: replace
          path: /cluster/controlPlane
          value:
            endpoint: https://${TOEM_CP_ENDPOINT}:6443
        - op: add
          path: /cluster/controllerManager/extraArgs
          value:
            cloud-provider: external
        - op: add
          path: /cluster/apiServer/extraArgs
          value:
            cloud-provider: external
        - op: add
          path: /cluster/network/cni
          value:
            name: none
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
            manifests:
              - https://github.com/equinix/cloud-provider-equinix-metal/releases/download/${CPEM_VERSION}/deployment.yaml

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      os: talos_v1
      billingCycle: hourly
      machineType: "${CONTROLPLANE_NODE_TYPE}"

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-worker"
spec:
  template:
    spec:
      os: talos_v1
      billingCycle: hourly
      machineType: "${WORKER_NODE_TYPE}"

---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-worker"
spec:
  template:
    spec:
      generateType: worker
      talosVersion: ${TALOS_VERSION}
      configPatches:
        - op: replace
          path: /cluster/controlPlane
          value:
            endpoint: https://${TOEM_CP_ENDPOINT}:6443
        - op: add
          path: /cluster/network
          value:
            cni: {}
        - op: add
          path: /cluster/network/cni
          value:
            name: none
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
            manifests:
              - https://github.com/equinix/cloud-provider-equinix-metal/releases/download/${CPEM_VERSION}/deployment.yaml
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: "external"

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-worker"
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    pool: worker-pool
spec:
  replicas: ${WORKER_MACHINE_COUNT}
  clusterName: ${CLUSTER_NAME}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
      pool: worker-pool
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
        pool: worker-pool
    spec:
      version: ${KUBERNETES_VERSION}
      clusterName: ${CLUSTER_NAME}
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-worker"
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-worker"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: PacketMachineTemplate